# Generated by Django 5.2.7 on 2025-10-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Acc', 'Accessories'), ('EC', 'Electronics & Computer'), ('LD', 'Laptops & Desktops'), ('MT', 'Mobiles & Tablets'), ('SSTV', 'SmartPhone & Smart TV')], max_length=5)),
                ('product_image', models.ImageField(upload_to='productimg')),
                ('product_status', models.TextField()),
            ],
        ),
    ]
